// frontend/src/app/features/auth/components/register-modal/register-modal.component.ts
import { Component, inject, effect, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FormBuilder,
  FormGroup,
  Validators,
  AbstractControl,
  ValidationErrors,
  ReactiveFormsModule,
} from '@angular/forms';
import { LucideAngularModule } from 'lucide-angular';
import { UiService } from '../../../../core/services/ui.service';
import { AuthService } from '../../../../core/services/auth';
import { catchError, takeUntil } from 'rxjs/operators';
import { of, Subject } from 'rxjs';

function passwordMatchValidator(control: AbstractControl): ValidationErrors | null {
  const password1 = control.get('password1');
  const password2 = control.get('password2');

  if (password1 && password2 && password1.value !== password2.value) {
    // Setting error on the password2 control
    password2.setErrors({ ...password2.errors, passwordMismatch: true });
    return { passwordMismatch: true };
  } else {
    if (password2?.hasError('passwordMismatch')) {
      const errors = { ...password2.errors };
      delete errors['passwordMismatch'];
      password2.setErrors(Object.keys(errors).length ? errors : null);
    }
  }
  return null;
}

@Component({
  selector: 'app-register-modal',
  standalone: true,
  imports: [CommonModule, LucideAngularModule, ReactiveFormsModule],
  template: `
    @if (ui.isRegisterModalOpen()) {
      <div
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm transition-opacity"
        (click)="closeModal()"
      >
        <div
          class="bg-white rounded-3xl shadow-2xl w-full max-w-md p-8 relative mx-4 transform transition-all border border-gray-100 max-h-[90vh] overflow-y-auto"
          (click)="$event.stopPropagation()"
        >
          <button
            (click)="closeModal()"
            class="absolute right-5 top-5 p-2 bg-gray-50 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-all"
            [disabled]="isLoading"
          >
            <lucide-icon name="x" class="w-5 h-5"></lucide-icon>
          </button>

          <div class="text-center mb-6 mt-2">
            <h2 class="text-3xl font-extrabold text-gray-900 mb-2 tracking-tight">Crear Cuenta</h2>
            <p class="text-gray-500 font-medium">Únete a Yonna Akademia hoy mismo</p>
          </div>

          @if (errorMessage) {
            <div
              class="mb-6 p-4 bg-red-50 border border-red-100 text-red-600 rounded-xl text-sm font-medium text-center"
            >
              {{ errorMessage }}
            </div>
          }
          @if (successMessage) {
            <div
              class="mb-6 p-4 bg-green-50 border border-green-100 text-green-700 rounded-xl text-sm font-medium text-center"
            >
              {{ successMessage }}
            </div>
          }

          <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4">
            <div>
              <label class="block text-sm font-semibold text-gray-700 mb-1.5"
                >Nombre</label
              >
              <input
                type="text"
                formControlName="first_name"
                class="w-full px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-orange/30 focus:border-brand-orange transition-all"
                [ngClass]="{
                  'border-red-300 focus:border-red-500 focus:ring-red-200':
                    isFieldInvalid('first_name'),
                }"
                placeholder="Ej. María"
                [disabled]="isLoading"
              />
              @if (isFieldInvalid('first_name')) {
                <p class="text-red-500 text-xs mt-1.5 font-medium">
                  El nombre es requerido.
                </p>
              }
            </div>
            <div>
              <label class="block text-sm font-semibold text-gray-700 mb-1.5"
                >Apellido</label
              >
              <input
                type="text"
                formControlName="last_name"
                class="w-full px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-orange/30 focus:border-brand-orange transition-all"
                [ngClass]="{
                  'border-red-300 focus:border-red-500 focus:ring-red-200':
                    isFieldInvalid('last_name'),
                }"
                placeholder="Ej. Rodríguez"
                [disabled]="isLoading"
              />
              @if (isFieldInvalid('last_name')) {
                <p class="text-red-500 text-xs mt-1.5 font-medium">
                  El apellido es requerido.
                </p>
              }
            </div>
            <div>
              <label class="block text-sm font-semibold text-gray-700 mb-1.5"
                >Correo Electrónico</label
              >
              <input
                type="email"
                formControlName="email"
                class="w-full px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-orange/30 focus:border-brand-orange transition-all"
                [ngClass]="{
                  'border-red-300 focus:border-red-500 focus:ring-red-200': isFieldInvalid('email'),
                }"
                placeholder="tu@email.com"
                [disabled]="isLoading"
              />
              @if (isFieldInvalid('email')) {
                <p class="text-red-500 text-xs mt-1.5 font-medium">
                  Por favor, ingresa un correo válido.
                </p>
              }
            </div>
            <div>
              <label class="block text-sm font-semibold text-gray-700 mb-1.5">Contraseña</label>
              <input
                type="password"
                formControlName="password1"
                class="w-full px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-orange/30 focus:border-brand-orange transition-all"
                [ngClass]="{
                  'border-red-300 focus:border-red-500 focus:ring-red-200':
                    isFieldInvalid('password1'),
                }"
                placeholder="Mínimo 6 caracteres"
                [disabled]="isLoading"
              />
              @if (isFieldInvalid('password1')) {
                @if (registerForm.get('password1')?.hasError('required')) {
                  <p class="text-red-500 text-xs mt-1.5 font-medium">La contraseña es requerida.</p>
                } @else if (registerForm.get('password1')?.hasError('minlength')) {
                  <p class="text-red-500 text-xs mt-1.5 font-medium">
                    La contraseña debe tener al menos 6 caracteres.
                  </p>
                }
              }
            </div>
            <div>
              <label class="block text-sm font-semibold text-gray-700 mb-1.5"
                >Confirmar Contraseña</label
              >
              <input
                type="password"
                formControlName="password2"
                class="w-full px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-brand-orange/30 focus:border-brand-orange transition-all"
                [ngClass]="{
                  'border-red-300 focus:border-red-500 focus:ring-red-200':
                    isFieldInvalid('password2'),
                }"
                placeholder="Repite tu contraseña"
                [disabled]="isLoading"
              />
              @if (
                isFieldInvalid('password2') &&
                registerForm.get('password2')?.hasError('required')
              ) {
                <p class="text-red-500 text-xs mt-1.5 font-medium">La confirmación es requerida.</p>
              }
              @if (
                registerForm.get('password2')?.hasError('passwordMismatch') &&
                registerForm.get('password2')?.touched
              ) {
                <p class="text-red-500 text-xs mt-1.5 font-medium">Las contraseñas no coinciden.</p>
              }
            </div>

            <button
              type="submit"
              [disabled]="registerForm.invalid || isLoading || successMessage !== ''"
              class="w-full bg-brand-orange text-white font-bold py-4 rounded-xl hover:bg-opacity-90 hover:shadow-lg hover:shadow-brand-orange/20 transition-all mt-6 text-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              @if (isLoading) {
                <svg
                  class="animate-spin h-5 w-5 text-white"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <circle
                    class="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    stroke-width="4"
                  ></circle>
                  <path
                    class="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                  ></path>
                </svg>
                Registrando...
              } @else {
                Completar Registro
              }
            </button>
          </form>

          <p class="text-center text-sm text-gray-600 mt-8 font-medium">
            ¿Ya tienes una cuenta?
            <button
              (click)="openLogin()"
              class="text-brand-green font-bold hover:underline ml-1"
              [disabled]="isLoading"
            >
              Ingresa aquí
            </button>
          </p>
        </div>
      </div>
    }
  `,
})
export class RegisterModalComponent implements OnDestroy {
  ui = inject(UiService);
  auth = inject(AuthService);
  fb = inject(FormBuilder);

  registerForm: FormGroup;
  isLoading = false;
  errorMessage = '';
  successMessage = '';

  private destroy$ = new Subject<void>();

  constructor() {
    this.registerForm = this.fb.group(
      {
        first_name: ['', [Validators.required]],
        last_name: ['', [Validators.required]],
        email: ['', [Validators.required, Validators.email]],
        password1: ['', [Validators.required, Validators.minLength(6)]],
        password2: ['', [Validators.required]],
      },
      { validators: passwordMatchValidator },
    );

    effect(() => {
      if (!this.ui.isRegisterModalOpen()) {
        this.resetForm();
      }
    });
  }

  isFieldInvalid(field: string): boolean {
    const control = this.registerForm.get(field);
    return !!(control && control.invalid && (control.dirty || control.touched));
  }

  onSubmit() {
    if (this.registerForm.invalid) {
      this.registerForm.markAllAsTouched();
      return;
    }

    this.isLoading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const { first_name, last_name, email, password1, password2 } = this.registerForm.value;

    this.auth
      .register({ first_name, last_name, email, password1, password2 })
      .pipe(
        takeUntil(this.destroy$),
        catchError((err) => {
          this.errorMessage =
            err.error?.detail ||
            err.error?.first_name?.[0] ||
            err.error?.last_name?.[0] ||
            err.error?.email?.[0] ||
            err.error?.password1?.[0] ||
            'Ocurrió un error en el registro.';
          this.isLoading = false;
          return of(null);
        }),
      )
      .subscribe((res) => {
        if (res) {
          this.isLoading = false;
          this.successMessage = '¡Cuenta creada con éxito! Iniciando sesión...';

          this.auth
            .login({ email, password: password1 })
            .pipe(takeUntil(this.destroy$))
            .subscribe({
              next: () => {
                setTimeout(() => {
                  this.ui.closeRegisterModal();
                }, 1000);
              },
              error: () => {
                this.successMessage = 'Registro exitoso. Por favor ingresa a tu cuenta.';
                setTimeout(() => {
                  this.ui.openLoginModal();
                }, 1500);
              },
            });
        }
      });
  }

  closeModal() {
    if (!this.isLoading) {
      this.ui.closeRegisterModal();
    }
  }

  openLogin() {
    this.ui.openLoginModal();
  }

  private resetForm() {
    this.registerForm.reset();
    this.errorMessage = '';
    this.successMessage = '';
    this.isLoading = false;
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

// frontend/src/components/auth/RegisterModal.jsx
import { useState } from 'react';
import { useGoogleLogin } from '@react-oauth/google';
import { useAuth } from '../../hooks/useAuth';
import Modal from '../common/Modal';
import Input from '../common/Input';
import Button from '../common/Button';

const RegisterModal = ({ isOpen, onClose, onSwitchToLogin }) => {
  const { register, loginWithGoogle } = useAuth();
  const [formData, setFormData] = useState({
    first_name: '',
    last_name: '',
    email: '',
    password1: '',
    password2: '',
  });
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
    if (errors[e.target.name]) {
      setErrors({
        ...errors,
        [e.target.name]: '',
      });
    }
  };

  const validateForm = () => {
    const newErrors = {};

    if (formData.password1 !== formData.password2) {
      newErrors.password2 = 'Las contraseñas no coinciden';
    }

    if (formData.password1.length < 8) {
      newErrors.password1 = 'La contraseña debe tener al menos 8 caracteres';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      return;
    }

    setLoading(true);

    const result = await register(formData);

    setLoading(false);

    if (result.success) {
      if (result.needsLogin) {
        // Si el backend no devuelve tokens, redirigir al login
        onSwitchToLogin();
      } else {
        onClose();
      }
      setFormData({
        first_name: '',
        last_name: '',
        email: '',
        password1: '',
        password2: '',
      });
      setErrors({});
    }
  };

  const googleRegister = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      setLoading(true);
      const result = await loginWithGoogle(tokenResponse.access_token);
      setLoading(false);
      
      if (result.success) {
        onClose();
      }
    },
    onError: () => {
      console.error('Google register failed');
    },
  });

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Registrarse">
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <Input
            label="Nombre"
            type="text"
            name="first_name"
            value={formData.first_name}
            onChange={handleChange}
            placeholder="Tu nombre"
            required
          />

          <Input
            label="Apellido"
            type="text"
            name="last_name"
            value={formData.last_name}
            onChange={handleChange}
            placeholder="Tu apellido"
            required
          />
        </div>

        <Input
          label="Correo Electrónico"
          type="email"
          name="email"
          value={formData.email}
          onChange={handleChange}
          placeholder="tu@correo.com"
          required
        />

        <Input
          label="Contraseña"
          type="password"
          name="password1"
          value={formData.password1}
          onChange={handleChange}
          placeholder="••••••••"
          error={errors.password1}
          required
        />

        <Input
          label="Confirmar Contraseña"
          type="password"
          name="password2"
          value={formData.password2}
          onChange={handleChange}
          placeholder="••••••••"
          error={errors.password2}
          required
        />

        <Button type="submit" disabled={loading}>
          {loading ? 'Registrando...' : 'Registrarse'}
        </Button>

        <div className="relative my-6">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-gray-300"></div>
          </div>
          <div className="relative flex justify-center text-sm">
            <span className="px-4 bg-white text-gray-500">o continúa con</span>
          </div>
        </div>

        <Button 
          variant="google" 
          onClick={() => googleRegister()} 
          type="button"
          disabled={loading}
        >
          <svg className="w-5 h-5" viewBox="0 0 24 24">
            <path
              fill="#4285F4"
              d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
            />
            <path
              fill="#34A853"
              d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
            />
            <path
              fill="#FBBC05"
              d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
            />
            <path
              fill="#EA4335"
              d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
            />
          </svg>
          Continuar con Google
        </Button>

        <p className="text-center text-sm text-gray-600 mt-4">
          ¿Ya tienes una cuenta?{' '}
          <button
            type="button"
            onClick={onSwitchToLogin}
            className="text-[#ff914d] font-semibold hover:underline"
          >
            Inicia sesión aquí
          </button>
        </p>
      </form>
    </Modal>
  );
};

export default RegisterModal;
